---
# Swap configuration tasks (zram + hibernation swapfile)

- name: Install zram-generator
  pacman:
    name: zram-generator
    state: present
  tags: swap, zram

- name: Configure zram
  template:
    src: zram-generator.conf.j2
    dest: /etc/systemd/zram-generator.conf
    mode: '0644'
  notify: restart systemd-zram-setup@zram0
  tags: swap, zram

- name: Create swapfile for hibernation
  command: dd if=/dev/zero of={{ swap.swapfile.path }} bs=1M count={{ swap.swapfile.size | regex_replace('G', '') | int * 1024 }}
  args:
    creates: "{{ swap.swapfile.path }}"
  when: swap.swapfile.enabled
  tags: swap, hibernation

- name: Set swapfile permissions
  file:
    path: "{{ swap.swapfile.path }}"
    mode: '0600'
    owner: root
    group: root
  when: swap.swapfile.enabled
  tags: swap, hibernation

- name: Format swapfile
  command: mkswap {{ swap.swapfile.path }}
  when: swap.swapfile.enabled
  changed_when: false
  tags: swap, hibernation

- name: Add swapfile to fstab
  mount:
    name: none
    src: "{{ swap.swapfile.path }}"
    fstype: swap
    opts: sw
    state: present
  when: swap.swapfile.enabled
  tags: swap, hibernation

- name: Enable swapfile
  command: swapon {{ swap.swapfile.path }}
  when: swap.swapfile.enabled
  changed_when: false
  failed_when: false
  tags: swap, hibernation

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes
  tags: swap, performance