---
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: kewlfft.aur
    version: ">=0.11.0"
  - name: community.archlinux
    version: ">=0.3.0"
