---
# Main tasks for system_hardening role

- name: Include kernel hardening tasks
  include_tasks: kernel.yml
  tags: kernel, hardening

- name: Include firewall configuration tasks
  include_tasks: firewall.yml
  tags: firewall
  when: firewall_enabled

- name: Include fail2ban configuration tasks
  include_tasks: fail2ban.yml
  tags: fail2ban
  when: fail2ban_enabled

- name: Include audit configuration tasks
  include_tasks: audit.yml
  tags: audit
  when: audit_enabled

- name: Include file permissions hardening tasks
  include_tasks: permissions.yml
  tags: permissions

- name: Include module blacklisting tasks
  include_tasks: modules.yml
  tags: modules

- name: Include security scanning setup tasks
  include_tasks: scanning.yml
  tags: scanning

- name: Include login security tasks
  include_tasks: login.yml
  tags: login

- name: Include network security tasks
  include_tasks: network.yml
  tags: network