# roles/users/tasks/main.yml
---
- name: Ensure required groups exist
  group:
    name: "{{ item }}"
    state: present
  loop:
    - wheel
    - audio
    - video
    - storage
    - optical
    - network
    - docker

- name: Create user LyeosMaouli
  user:
    name: LyeosMaouli
    comment: "Main Desktop User"
    shell: /bin/bash
    create_home: yes
    groups: wheel,audio,video,storage,optical,network
    append: yes
    state: present
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_type: rsa

- name: Configure passwordless sudo for wheel group
  copy:
    content: "%wheel ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/wheel_nopasswd
    mode: "0440"
    validate: "/usr/sbin/visudo -cf %s"

- name: Set proper home directory permissions
  file:
    path: /home/LyeosMaouli
    owner: LyeosMaouli
    group: LyeosMaouli
    mode: "0755"
    state: directory

- name: Create user SSH directory
  file:
    path: /home/LyeosMaouli/.ssh
    owner: LyeosMaouli
    group: LyeosMaouli
    mode: "0700"
    state: directory
