---
- name: Install systemd-boot
  shell: bootctl install
  args:
    creates: /boot/EFI/systemd/systemd-bootx64.efi
  when: ansible_firmware_type == "uefi"

- name: Configure systemd-boot loader
  template:
    src: loader.conf.j2
    dest: /boot/loader/loader.conf
    backup: true
  notify: update systemd-boot

- name: Get root partition UUID
  shell: blkid -s PARTUUID -o value {{ ansible_mounts | selectattr('mount', 'equalto', '/') | map(attribute='device') | first }}
  register: root_partuuid
  changed_when: false

- name: Create Arch Linux boot entry
  template:
    src: arch.conf.j2
    dest: /boot/loader/entries/arch.conf
    backup: true
  vars:
    root_uuid: "{{ root_partuuid.stdout }}"
  notify: update systemd-boot
