---
- name: Arch Linux Desktop Automation with Hyprland
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update package cache
      pacman:
        update_cache: true
      changed_when: false
      tags: always

    - name: Verify system requirements
      assert:
        that:
          - ansible_facts['distribution'] == "Archlinux"
          - ansible_facts['architecture'] == "x86_64"
        fail_msg: "This playbook requires Arch Linux x86_64"
      tags: always

  roles:
    - role: arch_base
      tags: ["base", "system"]
    - role: security_hardening
      tags: ["security", "hardening"]
    - role: bootloader
      tags: ["boot", "system"]
    - role: user_management
      tags: ["users", "security"]
    - role: hardware_support
      tags: ["hardware", "drivers"]
    - role: hyprland_desktop
      tags: ["desktop", "hyprland"]
    - role: applications
      tags: ["apps", "software"]
    - role: maintenance
      tags: ["maintenance", "automation"]

  post_tasks:
    - name: Final system verification
      debug:
        msg: "System configuration completed successfully!"
      tags: always
