# configs/ansible/roles/hyprland_desktop/tasks/main.yml
---
- name: Install Hyprland ecosystem packages
  pacman:
    name:
      - hyprland
      - xdg-desktop-portal-hyprland
      - qt5-wayland
      - qt6-wayland
      - wl-clipboard
      - grim
      - slurp
      - brightnessctl
      - playerctl
      - alacritty
      - firefox
      - thunar
    state: present

- name: Install AUR packages
  kewlfft.aur.aur:
    name:
      - waybar-hyprland
      - wofi
      - hyprpaper
      - hypridle
      - hyprlock
      - wlogout
    use: yay
    state: present
  become_user: "{{ user }}"

- name: Create Hyprland configuration directories
  file:
    path: "{{ home_dir }}/.config/{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
  loop:
    - hypr
    - waybar
    - wofi
    - alacritty

- name: Configure Hyprland
  template:
    src: hyprland.conf.j2
    dest: "{{ home_dir }}/.config/hypr/hyprland.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  notify: reload_hyprland

- name: Configure Waybar
  template:
    src: waybar/config.json.j2
    dest: "{{ home_dir }}/.config/waybar/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Configure Wofi
  template:
    src: wofi.conf.j2
    dest: "{{ home_dir }}/.config/wofi/config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Setup SDDM for Hyprland
  template:
    src: sddm.conf.j2
    dest: /etc/sddm.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart_sddm

- name: Create Hyprland desktop session
  copy:
    content: |
      [Desktop Entry]
      Name=Hyprland
      Comment=An intelligent dynamic tiling Wayland compositor
      Exec=Hyprland
      Type=Application
    dest: /usr/share/wayland-sessions/hyprland.desktop
    owner: root
    group: root
    mode: "0644"
