---
galaxy_info:
  role_name: aur_packages
  author: lyeosmaouli
  description: AUR package management with yay for Arch Linux
  license: MIT
  min_ansible_version: "2.12"
  
  platforms:
    - name: ArchLinux
      versions:
        - all
        
  galaxy_tags:
    - archlinux
    - aur
    - yay
    - packages
    - security

dependencies: []