# roles/packages/tasks/main.yml
---
- name: Create AUR builder user
  user:
    name: aur_builder
    create_home: yes
    shell: /bin/bash
    system: yes

- name: Configure sudo for AUR builder
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: yes
    mode: "0644"
    validate: "visudo -cf %s"

- name: Install base development tools
  pacman:
    name:
      - base-devel
      - git
    state: present

- name: Install Google Chrome from AUR
  kewlfft.aur.aur:
    name: google-chrome
    use: yay
    state: present
    aur_only: yes
  become: yes
  become_user: aur_builder
