# VLC with complete codec support
- name: Install VLC and multimedia codecs
  pacman:
    name:
      # Core VLC
      - vlc

      # Essential multimedia framework
      - ffmpeg
      - gst-libav
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly

      # Video codecs
      - x264
      - x265
      - libvpx
      - aom
      - dav1d
      - rav1e
      - libde265
      - libmpeg2
      - libtheora
      - xvidcore

      # Audio codecs
      - lame
      - libvorbis
      - opus
      - libfdk-aac
      - faac
      - faad2
      - libmad
      - speex
      - flac
      - wavpack

      # Hardware acceleration
      - libva
      - libvdpau
      - mesa-vdpau

      # DVD/Blu-ray support
      - libdvdread
      - libdvdcss
      - libdvdnav
      - libbluray

    state: present
