---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  children:
    desktops:
      hosts:
        localhost:
      vars:
        desktop_environment: hyprland
        install_development_tools: true
        install_multimedia: true
