---
- name: Create AUR builder user
  user:
    name: aur_builder
    create_home: true
    group: wheel
    system: true

- name: Allow AUR builder to run pacman without password
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: "visudo -cf %s"

- name: Install yay AUR helper
  become: true
  become_user: aur_builder
  shell: |
    cd /tmp
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si --noconfirm
  args:
    creates: /usr/bin/yay
