---
- name: Install fail2ban
  pacman:
    name: fail2ban
    state: present

- name: Configure fail2ban jail
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: true
  notify: restart fail2ban

- name: Enable and start fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: true
