---
- name: Install UFW
  pacman:
    name: ufw
    state: present

- name: Reset UFW to defaults
  ufw:
    state: reset

- name: Configure UFW defaults
  ufw:
    default: deny
    direction: incoming

- name: Allow SSH
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
