---
galaxy_info:
  role_name: arch_base
  author: LyeosMaouli
  description: Base Arch Linux system configuration and optimization
  license: GPL-3.0-or-later
  min_ansible_version: "2.12"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - archlinux
    - base
    - configuration

dependencies: []

argument_specs:
  main:
    short_description: Configure base Arch Linux system
    options:
      base_packages:
        description: List of base packages to install
        type: list
        default: []
      enable_multilib:
        description: Enable multilib repository
        type: bool
        default: false
      optimize_makepkg:
        description: Optimize makepkg configuration
        type: bool
        default: true
