# configs/ansible/roles/hardware_optimization/tasks/main.yml
---
- name: Configure Intel GPU optimizations
  template:
    src: intel_gpu.conf.j2
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    owner: root
    group: root
    mode: "0644"
  when: gpu_driver == "intel"

- name: Configure Intel GPU kernel modules
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: "^MODULES="
    line: "MODULES=(i915)"
  notify: rebuild_initramfs

- name: Configure Intel GPU module options
  copy:
    content: |
      options i915 enable_guc=2
      options i915 enable_fbc=1
      options i915 fastboot=1
    dest: /etc/modprobe.d/i915.conf
    owner: root
    group: root
    mode: "0644"

- name: Configure hibernation for laptop
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet resume=UUID={{ swap_uuid }}"'
  when: "'laptop' in inventory_hostname"
  notify: update_grub
