# configs/ansible/playbooks/maintenance.yml
---
- name: System Maintenance and Updates
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:
    main_user: lyeosmaouli

  pre_tasks:
    - name: Update package cache
      pacman:
        update_cache: true
        upgrade: true

  roles:
    - role: base_system
      tags: ["system", "maintenance"]

    - role: aur_packages
      tags: ["aur", "updates"]

    - role: monitoring
      tags: ["monitoring", "health"]

  post_tasks:
    - name: Clean package cache
      command: pacman -Sc --noconfirm
      changed_when: false

    - name: System maintenance completed
      debug:
        msg: "System maintenance completed successfully!"
