---
- name: Install power management packages
  pacman:
    name: "{{ power_packages }}"
    state: present

- name: Configure TLP
  include_tasks: tlp.yml

- name: Configure hibernation
  include_tasks: hibernation.yml
  when: enable_hibernation | default(true)

- name: Configure CPU frequency scaling
  include_tasks: cpu-scaling.yml
