---
- name: Install TLP
  pacman:
    name:
      - tlp
      - tlp-rdw
    state: present

- name: Configure TLP
  template:
    src: tlp.conf.j2
    dest: /etc/tlp.conf
    backup: true
  notify: restart tlp

- name: Enable and start TLP
  systemd:
    name: tlp
    state: started
    enabled: true

- name: Mask power-profiles-daemon
  systemd:
    name: power-profiles-daemon
    masked: true
