# roles/boot_config/tasks/main.yml
---
- name: Install systemd-boot
  command: bootctl install
  args:
    creates: /boot/EFI/systemd/systemd-bootx64.efi
  notify: update bootloader

- name: Create loader configuration
  template:
    src: loader.conf.j2
    dest: /boot/loader/loader.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Get root partition UUID
  command: "blkid -s UUID -o value {{ root_device }}"
  register: root_uuid
  changed_when: false

- name: Create main boot entry
  template:
    src: arch.conf.j2
    dest: /boot/loader/entries/arch.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Create fallback boot entry
  template:
    src: arch-fallback.conf.j2
    dest: /boot/loader/entries/arch-fallback.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
